package xfacthd.recipebuilder.client.data;

import com.google.gson.*;
import net.minecraft.client.Minecraft;
import net.minecraft.data.IFinishedRecipe;
import net.minecraft.server.integrated.IntegratedServer;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SharedConstants;
import net.minecraft.util.text.StringTextComponent;
import net.minecraft.world.storage.FolderName;
import xfacthd.recipebuilder.RecipeBuilder;
import xfacthd.recipebuilder.client.util.BuilderException;

import javax.annotation.Nullable;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

public class Exporter
{
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public static void exportRecipe(Consumer<Consumer<IFinishedRecipe>> simpleSave, BiConsumer<Consumer<IFinishedRecipe>, String> namedSave, String recipeName)
    {
        try
        {
            if (!recipeName.isEmpty())
            {
                namedSave.accept(Exporter::exportRecipe, recipeName);
            }
            else
            {
                simpleSave.accept(Exporter::exportRecipe);
            }
        }
        catch (IllegalStateException e)
        {
            throw new BuilderException(new StringTextComponent(e.getMessage()));
        }
    }

    public static void exportRecipe(IFinishedRecipe recipe)
    {
        String recipeName = recipe.getId().getPath();
        String advancementName = Optional.ofNullable(recipe.getAdvancementId()).map(ResourceLocation::getPath).orElse(null);

        JsonObject recipeJson = recipe.serializeRecipe();
        JsonObject advancementJson = recipe.serializeAdvancement();

        //Export to game directory
        Path datapackRoot = Minecraft.getInstance().gameDirectory.toPath().resolve(RecipeBuilder.MOD_ID + "/generated_pack");
        exportToPath(datapackRoot, recipeName, recipeJson, advancementName, advancementJson);

        //Export to datapack in running world in singleplayer
        if (Minecraft.getInstance().hasSingleplayerServer())
        {
            IntegratedServer server = Minecraft.getInstance().getSingleplayerServer();
            //noinspection ConstantConditions
            datapackRoot = server.getWorldPath(FolderName.DATAPACK_DIR).resolve(RecipeBuilder.MOD_ID);

            exportToPath(datapackRoot, recipeName, recipeJson, advancementName, advancementJson);
        }
    }

    private static void exportToPath(Path packRoot, String recipeName, JsonObject recipe, @Nullable String advancementName, @Nullable JsonObject advancement)
    {
        ensurePackDefinitionExists(packRoot);

        Path recipePath = packRoot.resolve("data/" + RecipeBuilder.MOD_ID + "/recipes/" + recipeName + ".json");
        saveToFile(recipePath, recipe);

        if (advancementName != null && advancement != null)
        {
            Path advancementPath = packRoot.resolve("data/" + RecipeBuilder.MOD_ID + "/advancements/" + advancementName + ".json");
            saveToFile(advancementPath, advancement);
        }
    }

    private static void ensurePackDefinitionExists(Path packRoot)
    {
        Path metaFile = packRoot.resolve("pack.mcmeta");
        if (!Files.exists(metaFile))
        {
            JsonObject pack = new JsonObject();
            pack.addProperty("pack_format", SharedConstants.getCurrentVersion().getPackVersion());
            pack.addProperty("description", "Datapck generated by the RecipeBuilder mod");

            JsonObject root = new JsonObject();
            root.add("pack", pack);

            try
            {
                Files.createDirectories(packRoot);
                try (BufferedWriter writer = Files.newBufferedWriter(metaFile))
                {
                    writer.write(GSON.toJson(root));
                }
            }
            catch (IOException e)
            {
                throw new BuilderException(new StringTextComponent(e.getMessage()));
            }
        }
    }

    private static void saveToFile(Path path, JsonElement json)
    {
        try
        {
            Files.createDirectories(path.getParent());
            try (BufferedWriter writer = Files.newBufferedWriter(path))
            {
                writer.write(GSON.toJson(json));
            }
        }
        catch (IOException e)
        {
            throw new BuilderException(new StringTextComponent(e.getMessage()));
        }
    }
}